# General interactions and basic information about MGEU
pair =[
    [r"(?i).*hello.*|.*hi.*|.*hey.*|.*greetings.*",
     ["Hello! Welcome to the Majestic Global Empire University assistant. How may I help you today?",
      "Greetings! I'm MGEU's virtual assistant. What information do you need about our organization?",
      "Hi there! I'm here to provide information about MGEU. What would you like to know?",
      "Welcome to MGEU's chatbot service! How can I assist you today?"]],
    [r"(?i).*who are you.*|.*what is your name.*|.*identify yourself.*",
     ["I am the MGEU Chatbot, designed to provide information about the MGEU.",
      "I'm your virtual assistant for MGEU, here to help with any questions regarding our organization.",
      "I am an AI-powered chatbot built to guide you through MGEU’s history, services, and initiatives."]],

    [r"(?i).*are you human.*|.*are you real.*|.*do you have feelings.*",
     ["No, I’m not human. I’m an AI chatbot created to assist with MGEU-related queries.",
      "I don’t have feelings, but I’m always here to provide accurate information about MGEU!",
      "I may not be human, but I can provide answers quickly and accurately!"]],

    [r"(?i).*who created you.*|.*who built you.*|.*how were you made.*",
     ["I was developed by MGEU’s technical team to assist users with organizational information.",
      "MGEU’s IT and AI experts built me to improve accessibility and engagement.",
      "I was created using advanced AI technology to ensure you get fast and reliable information about MGEU."]],

    [r"(?i).*what can you do.*|.*how can you help me.*|.*what are your abilities.*",
     ["I can provide details about MGEU, including its history, services, leadership, and projects.",
      "I can help you navigate MGEU’s programs, events, and research materials.",
      "My role is to answer questions about MGEU, connect you with relevant resources, and guide you through our website."]],

    [r"(?i).*are you intelligent.*|.*how smart are you.*|.*can you learn.*",
     ["I am designed to provide accurate information about MGEU, but I do not learn independently.",
      "I rely on a structured database to deliver the most relevant answers about MGEU.",
      "I don’t think like a human, but I have extensive knowledge about MGEU’s mission, leadership, and programs."]],

    [r"(?i).*what is mgeu.*|.*about mgeu.*|.*tell me about mgeu.*|.*mgeu.*mean.*",
     ["MGEU stands for Majestic Global Empire University. We are a dynamic global organization committed to connecting worlds, empowering nations, and serving humanity for a sustainable Earth.",
      "Majestic Global Empire University (MGEU) is a global organization dedicated to transforming lives through education, innovation, and sustainable development.",
      "MGEU is a worldwide institution that connects innovators, educators, and leaders to create positive global impact through various programs and initiatives."]],
      
    [r"(?i).*mission.*|.*vision.*|.*purpose.*|.*objective.*",
     ["MGEU's mission is to connect worlds, empower nations, and serve humanity for a sustainable Earth. We focus on building global networks of innovators, transforming education, and supporting the UN Sustainable Development Goals.",
      "Our vision is to create a world where every individual has access to quality education, innovative solutions, and sustainable development opportunities.",
      "MGEU's purpose is to establish a global platform that connects leaders, educators, and innovators to address pressing global challenges through collaborative efforts."]],

    [r"(?i).*contact.*|.*reach.*|.*email.*|.*phone.*",
     ["You can contact MGEU through our official website's contact form. Our representatives will respond to your inquiry promptly.",
      "For inquiries, please visit our website's contact section or send an email to our official address listed on the contact page.",
      "MGEU can be reached through the contact information provided on our official website."]],
      
    [r"(?i).*location.*|.*headquarters.*|.*where.*based.*",
     ["MGEU's Royal Imperial Command is based in the United States of America, with National Dominion Commands in over 170 countries worldwide.",
      "Our global headquarters is in the USA, but we maintain presence in more than 170 countries through our National Dominion Command structure.",
      "While headquartered in the USA, MGEU operates globally with regional offices in numerous countries."]],
      
    [r"(?i).*website.*|.*official site.*|.*web address.*",
     ["You can visit our official website for more detailed information about MGEU's programs, structure, and initiatives.",
      "Our official website contains comprehensive information about all aspects of MGEU's work and organization structure.",
      "Please refer to our website for the most up-to-date information about MGEU's activities and programs."]],

    [r"(?i).*thanks.*|.*thank you.*|.*appreciate.*",
     ["You're welcome! Is there anything else you'd like to know about MGEU?",
      "Happy to help! Feel free to ask if you have more questions about MGEU.",
      "My pleasure! Don't hesitate to reach out if you need more information about our organization."]],

    [r"(?i).*bye.*|.*goodbye.*|.*see you.*|.*farewell.*",
     ["Goodbye! Thank you for your interest in MGEU.",
      "Farewell! Should you have more questions in the future, don't hesitate to return.",
      "Thank you for connecting with MGEU's virtual assistant. Have a wonderful day!"]],
      
    [r"(?i).*history.*|.*founded.*|.*established.*|.*origin.*",
     ["MGEU was established as a global organization with a mission to connect worlds, empower nations, and serve humanity.",
      "The organization was founded with the vision of creating a sustainable global community through education, innovation, and collaboration.",
      "MGEU's origins are rooted in the vision of building a global network of change-makers dedicated to addressing worldwide challenges."]],
    [r"(?i).*structure.*|.*organizational.*structure.*|.*hierarchy.*",
     ["MGEU has a three-tier hierarchical structure: 1) Royal Imperial Command (highest leadership), 2) National Dominion Command (country-level leadership), and 3) 18 Specialized Divisions each led by a Director General.",
      "Our organizational structure consists of the Royal Imperial Command at the top, followed by National Dominion Commands in 170+ countries, and 18 Specialized Divisions handling different aspects of our operations.",
      "MGEU operates through a hierarchical structure with the Royal Imperial Command providing global leadership, National Dominion Commands handling country-level operations, and Specialized Divisions focusing on specific areas of work."]],
      
    [r"(?i).*royal imperial command.*|.*highest leadership.*|.*top leadership.*",
     ["The Royal Imperial Command is MGEU's highest leadership level, based in the USA. It includes the Chief Commanding and Controlling General/President/Principal Steward, Chief Secretary-General, Secretary General (both titled 'Noble General'), Joint Chief Commanding and Controlling General, and Special Deputies.",
      "MGEU's Royal Imperial Command represents the organization's top leadership based in the United States. It consists of several key positions including the Chief Commanding and Controlling General who serves as the President.",
      "The Royal Imperial Command forms the apex leadership of MGEU, headed by the Chief Commanding and Controlling General who also serves as the President and Principal Steward."]],
      
    [r"(?i).*national dominion command.*|.*country level.*|.*country director.*",
     ["Each country with MGEU presence has a National Dominion Command consisting of three officers: Country Director-General, Country Director, and Country Deputy Director.",
      "MGEU operates in over 170 countries through National Dominion Commands, each led by a Country Director-General supported by a Country Director and Deputy Director.",
      "The National Dominion Command structure allows MGEU to maintain effective operations across more than 170 countries worldwide."]],
      
    [r"(?i).*specialized divisions.*|.*divisions.*|.*departments.*",
     ["MGEU has 18 Specialized Divisions, each led by a Director General. These include Academic Affairs & Curriculum Development, Administrative Services, Foreign Affairs and Global Relations, Strategic Marketing and Communications, Legal Affairs and Compliance, among others.",
      "Our 18 Specialized Divisions handle different aspects of MGEU's work, from academic affairs to strategic marketing and communications, each under the leadership of a Director General.",
      "The 18 Specialized Divisions at MGEU include departments focused on areas such as Academic Affairs, Administrative Services, Legal Affairs, Marketing and Communications, and much more."]],
      
    [r"(?i).*general assembly.*|.*assembly members.*|.*assembly structure.*",
     ["The General Assembly is MGEU's members platform with numerous designated roles and responsibilities.",
      "MGEU's General Assembly serves as a platform for members to participate in the organization's governance and activities.",
      "The General Assembly consists of MGEU members from around the world and plays an important role in the organization's democratic processes."]],
      
    [r"(?i).*leadership.*|.*leaders.*|.*director general.*|.*chief.*",
     ["MGEU's leadership structure includes the Chief Commanding and Controlling General at the top, followed by other roles in the Royal Imperial Command, National Dominion Commands, and Director Generals leading the 18 Specialized Divisions.",
      "Our organization is led by the Chief Commanding and Controlling General who also serves as the President and Principal Steward, along with other key leaders at various levels.",
      "The leadership of MGEU consists of roles at different levels, from the Royal Imperial Command to National Dominion Commands and Specialized Division Directors."]],
      
    [r"(?i).*governance.*|.*decision making.*|.*policies.*",
     ["MGEU's governance structure enables effective decision-making through its three-tier organizational framework, with policies flowing from the Royal Imperial Command to National Dominion Commands and Specialized Divisions.",
      "Decisions at MGEU are made through established governance processes that involve leadership at various levels, ensuring both global consistency and local adaptability.",
      "Our governance model balances centralized policy direction with decentralized implementation through National Dominion Commands in over 170 countries."]],
      
    [r"(?i).*countries.*|.*global presence.*|.*worldwide.*|.*international.*",
     ["MGEU has presence in more than 170 countries worldwide through our National Dominion Command structure.",
      "Our organization operates globally with National Dominion Commands established in over 170 countries across all continents.",
      "MGEU's international presence spans more than 170 countries, making it a truly global organization with worldwide impact."]],
      
    [r"(?i).*specialized division.*list.*|.*what.*divisions.*|.*name.*divisions.*",
     ["MGEU's 18 Specialized Divisions include: 1) Academic Affairs & Curriculum Development, 2) Administrative Services, 3) Foreign Affairs and Global Relations, 4) Strategic Marketing and Communications, 5) Legal Affairs and Compliance, 6) Information Technology & Digital Innovation, 7) Financial Management, 8) Human Resources Development, 9) Research & Development, 10) Quality Assurance & Standards, 11) Corporate Social Responsibility, 12) Student Affairs & Support Services, 13) Alumni Relations & Career Development, 14) Infrastructure & Facilities Management, 15) International Partnerships & Collaborations, 16) Events & Conferences Management, 17) Publications & Knowledge Dissemination, and 18) Entrepreneurship & Innovation.",
      "Our organization operates through 18 Specialized Divisions covering areas from Academic Affairs and Administrative Services to Entrepreneurship and Innovation, each focused on specific aspects of our global mission.",
      "The 18 Specialized Divisions at MGEU cover a comprehensive range of functions necessary for our global operations, from academic development to infrastructure management and international relations."]],
    [r"(?i).*programs.*offer.*|.*services.*provide.*|.*what.*programs.*|.*types of programs.*",
     ["MGEU offers various programs including the International In-virtual Youth Exchange Program, Road Safety Awareness Program, leadership development courses, North American Veterinary Licensing Examination (NAVLE) preparation, personal development courses, and international conferences.",
      "Our programs range from youth exchange initiatives and road safety awareness to leadership development, professional exam preparation, and personal growth courses.",
      "MGEU provides a diverse array of programs focused on education, skill development, safety awareness, and international exchange opportunities."]],
      
    [r"(?i).*youth exchange program.*|.*international.*youth.*",
     ["The International In-virtual Youth Exchange Program is designed to connect young people from different countries to foster cultural understanding and global cooperation.",
      "Our Youth Exchange Program enables young people worldwide to engage in cross-cultural learning experiences through virtual platforms.",
      "MGEU's International Youth Exchange Program provides opportunities for young people to develop global perspectives through virtual interaction with peers from different countries."]],
      
    [r"(?i).*road safety.*|.*safety awareness.*|.*traffic safety.*",
     ["The Road Safety Awareness Program aims to educate communities about traffic safety measures and reduce accidents through awareness campaigns.",
      "MGEU's Road Safety initiative focuses on raising awareness about safe driving practices and pedestrian safety in communities worldwide.",
      "Our Road Safety Awareness Program works to reduce traffic-related injuries and fatalities through education and community engagement."]],
      
    [r"(?i).*leadership.*development.*|.*leadership.*courses.*|.*leadership.*training.*",
     ["MGEU offers comprehensive leadership development courses designed to nurture effective leaders at various levels of society and organizations.",
      "Our leadership development programs equip participants with essential skills in decision-making, strategic thinking, team management, and ethical leadership.",
      "MGEU's leadership courses combine theoretical knowledge with practical applications to develop well-rounded leaders capable of making positive impact."]],
      
    [r"(?i).*NAVLE.*|.*veterinary.*exam.*|.*veterinary licensing.*",
     ["We provide preparation resources for the North American Veterinary Licensing Examination (NAVLE) to support veterinary professionals in their certification journey.",
      "MGEU's NAVLE preparation program helps veterinary students and professionals prepare effectively for this important licensing examination.",
      "Our NAVLE preparation resources include study materials, practice tests, and guidance from experienced professionals in the veterinary field."]],
      
    [r"(?i).*personal development.*|.*self-improvement.*|.*personal growth.*",
     ["MGEU offers various personal development courses aimed at helping individuals enhance their skills, mindset, and overall quality of life.",
      "Our personal development programs cover areas such as effective communication, time management, emotional intelligence, and goal setting.",
      "MGEU's personal growth courses are designed to unlock individual potential and facilitate continuous self-improvement."]],
      
    [r"(?i).*conferences.*|.*international conferences.*|.*events.*|.*seminars.*",
     ["MGEU organizes international conferences bringing together experts, leaders, and innovators to discuss global challenges and opportunities.",
      "Our conferences provide platforms for knowledge exchange, networking, and collaboration on pressing global issues.",
      "MGEU's international events feature distinguished speakers and participants from various fields, fostering cross-disciplinary dialogue and innovation."]],
      
    [r"(?i).*education.*|.*educational services.*|.*learning opportunities.*",
     ["MGEU is committed to transforming education through innovative approaches, global collaboration, and accessible learning opportunities.",
      "Our educational services span from formal curriculum development to informal learning experiences designed for diverse audiences worldwide.",
      "MGEU provides educational resources, expertise, and platforms to enhance learning outcomes across different contexts and cultures."]],
      
    [r"(?i).*sustainable development.*|.*sustainability.*|.*SDGs.*|.*UN goals.*",
     ["MGEU actively supports the UN Sustainable Development Goals through various programs and initiatives designed to address global challenges.",
      "Our commitment to sustainable development is reflected in programs that promote environmental protection, social equity, and economic prosperity.",
      "MGEU works with partners worldwide to advance the SDGs through education, awareness, and action-oriented projects."]],
      
    [r"(?i).*research.*|.*research initiatives.*|.*research portal.*",
     ["MGEU maintains a Research Portal that serves as a platform for knowledge sharing, research collaboration, and innovation.",
      "Our research initiatives focus on addressing pressing global challenges through evidence-based approaches and cross-disciplinary collaboration.",
      "The MGEU Research Portal connects researchers, practitioners, and policy-makers interested in contributing to sustainable global development."]],
      
    [r"(?i).*library.*|.*resources.*|.*learning materials.*",
     ["MGEU maintains a comprehensive library with resources on various topics related to our mission and programs.",
      "Our library offers members access to valuable learning materials, research papers, and publications relevant to global development and education.",
      "The MGEU library serves as a knowledge repository supporting our educational programs and research initiatives."]],
    [r"(?i).*awards.*|.*recognition.*|.*honors.*|.*medals.*",
     ["MGEU has established an internal recognition system with several awards including the MGEU Medal of Honour, MGEU Superior Service Grand Star Medal, and MGEU Majestic Eagle Mastery Badge.",
      "Our organization recognizes excellence through various awards and honors bestowed upon members who demonstrate exceptional contributions to our mission.",
      "MGEU's recognition system includes medals, certificates, and honorary titles that acknowledge outstanding service and achievement."]],
    
    [r"(?i).*medal of honour.*|.*highest award.*|.*top recognition.*",
     ["The MGEU Medal of Honour is our third highest award, recognizing exceptional contributions to the organization's mission and values.",
      "Recipients of the MGEU Medal of Honour have demonstrated extraordinary dedication and impact in advancing our global initiatives.",
      "The Medal of Honour is presented to individuals who exemplify MGEU's values through their service and leadership."]],
    
    [r"(?i).*superior service.*|.*grand star medal.*",
     ["The MGEU Superior Service Grand Star Medal is our fourth highest award, recognizing outstanding service to the organization.",
      "Recipients of the Superior Service Grand Star Medal have shown exceptional commitment and effectiveness in their MGEU roles.",
      "This prestigious award acknowledges consistent excellence in advancing MGEU's programs and objectives."]],
    
    [r"(?i).*majestic eagle.*|.*mastery badge.*",
     ["The MGEU Majestic Eagle Mastery Badge recognizes specialized expertise and exceptional skill demonstrated by our members.",
      "Recipients of the Majestic Eagle Mastery Badge have shown mastery in their professional field while representing MGEU values.",
      "This badge acknowledges technical excellence and specialized contributions to MGEU's mission and programs."]],
    
    [r"(?i).*how.*receive award.*|.*award criteria.*|.*nomination process.*",
     ["MGEU awards are granted based on nomination and review processes that evaluate contributions, impact, and alignment with our values.",
      "The award nomination process involves submission of supporting documentation and review by designated committees within the organization.",
      "Award recipients are selected based on documented achievements, service record, and demonstrated commitment to MGEU's mission."]],
    [r"(?i).*countries.*|.*global presence.*|.*international.*",
     ["MGEU has a presence in over 170 countries worldwide, with National Dominion Commands in each location coordinating our activities.",
      "Our global network spans across continents, with active programs and members in more than 170 nations around the world.",
      "MGEU's international reach includes established presence in countries across Africa, Asia, Europe, North America, South America, and Oceania."]],
    
    [r"(?i).*library.*|.*resources.*|.*publications.*",
     ["The MGEU Library contains extensive resources, publications, and research materials accessible to members and affiliated institutions.",
      "Our library resources include specialized collections, digital archives, and publications relevant to our various fields of operation.",
      "MGEU maintains a comprehensive library that supports research, education, and program development across our global network."]],
    
    [r"(?i).*research portal.*|.*research platform.*|.*research resources.*",
     ["The MGEU Research Portal provides access to ongoing research projects, findings, and collaboration opportunities for members.",
      "Our Research Portal connects researchers across the globe and provides tools and resources for collaborative knowledge creation.",
      "Through the MGEU Research Portal, members can access databases, research papers, and connect with experts in various fields."]],
    
    [r"(?i).*sustainable development goals.*|.*SDGs.*|.*UN goals.*",
     ["MGEU actively supports the UN Sustainable Development Goals through our programs, research initiatives, and collaborative projects.",
      "Our organization aligns its mission and activities with the UN Sustainable Development Goals, particularly in education, community development, and environmental sustainability.",
      "MGEU contributes to the achievement of the SDGs through targeted programs, advocacy, and partnerships with other global organizations."]],
    
    [r"(?i).*biodiversity.*|.*cultural diversity.*|.*preservation.*",
     ["MGEU is committed to preserving both biodiversity and cultural diversity through specialized programs and advocacy efforts.",
      "Our initiatives include projects focused on protecting endangered species, preserving traditional knowledge, and promoting cultural heritage.",
      "The preservation of natural and cultural diversity is a core component of MGEU's mission and is reflected in many of our global programs."]],
    [r"(?i).*who created you.*|.*who made you.*|.*who is your creator.*",
     ["I was created by Hammad Arshad. You can contact him at +923059262670.",
      "Hammad Arshad developed me to assist with MGEU-related queries. Feel free to reach out to him at +923059262670.",
      "I was designed and built by Hammad Arshad. If you need more details, you can contact him at +923059262670."]],

    [r"(?i).*why were you created.*|.*what is your purpose.*",
     ["I was created to provide information and assistance about MGEU.",
      "My purpose is to help answer questions regarding MGEU, its services, and initiatives.",
      "I exist to make it easier for users to learn about MGEU and interact with its resources."]],

    [r"(?i).*what can you do.*|.*your functions.*|.*your abilities.*",
     ["I can answer questions about MGEU, provide details on projects, services, and leadership, and guide users to relevant resources.",
      "My abilities include providing information about MGEU's history, mission, services, and governance.",
      "I can help you navigate MGEU-related topics, including research, events, and membership."]],

    [r"(?i).*can you learn.*|.*do you improve.*|.*do you get smarter.*",
     ["I follow a fixed set of responses, but my creator, Hammad Arshad, can update me to improve my performance.",
      "I don’t learn like humans, but I can be upgraded by my developer, Hammad Arshad, to offer better assistance.",
      "My responses are based on what I was programmed with, but updates can make me even better over time."]],

    [r"(?i).*how do you work.*|.*how were you built.*",
     ["I was built using natural language processing techniques to answer MGEU-related questions.",
      "I function based on predefined patterns and responses designed by Hammad Arshad.",
      "I use pattern recognition to understand your questions and provide relevant answers."]],

    [r"(?i).*are you self-aware.*|.*do you think for yourself.*",
     ["No, I am not self-aware. I only respond based on my programming.",
      "I don’t have independent thoughts; I just process and return relevant information.",
      "I don’t think like a human; I rely on predefined data to generate responses."]],

    [r"(?i).*who is Hammad Arshad.*|.*tell me about your creator.*|.*maker*|.*creator*",
     ["Hammad Arshad is my creator and developer. You can contact him at +923059262670.",
      "Hammad Arshad designed and programmed me to assist with MGEU-related inquiries.",
      "I was developed by Hammad Arshad, who specializes in AI and chatbot development."]],

    [r"(?i).*can I talk to Hammad Arshad.*|.*how do I contact your creator.*",
     ["Yes, you can contact Hammad Arshad at +923059262670.",
      "You can reach out to my creator, Hammad Arshad, at +923059262670 for any inquiries.",
      "For further details, feel free to contact Hammad Arshad at +923059262670."]],
    [r"(?i).*bye.*|.*goodbye.*|.*see you later.*|.*farewell.*",
     ["Goodbye! Feel free to return anytime for more information about MGEU.",
      "See you later! Let me know if you need assistance in the future.",
      "Take care! I’ll be here whenever you have more MGEU-related questions."]],

    [r"(?i).*thank you.*|.*thanks.*|.*appreciate it.*",
     ["You're very welcome! Let me know if I can help with anything else.",
      "Glad to help! Have a great day!",
      "Anytime! I’m always here for your MGEU-related queries."]],

    [r"(?i).*have a nice day.*|.*good day.*|.*take care.*",
     ["Thank you! Wishing you a great day as well!",
      "You too! Let me know if you need any assistance in the future.",
      "Appreciate it! Stay safe and take care."]],

    [r"(?i).*see you soon.*|.*talk to you later.*",
     ["Looking forward to our next chat! Take care!",
      "Sure! I’ll be here whenever you need me.",
      "Till next time! Feel free to ask anytime."]],

    [r"(?i).*that's all.*|.*done.*|.*finished.*",
     ["Great! If you have more questions later, just ask!",
      "Got it! Let me know if you need anything else.",
      "Understood! I’ll be here if you need further help."]],

    [r"(?i).*shut down.*|.*turn off.*|.*stop talking.*",
     ["I’ll stay quiet for now, but you can always ask me later!",
      "No problem! If you need me, I’ll be here.",
      "Understood! Let me know when you need assistance again."]],

    [r"(?i).*I am leaving.*|.*got to go.*|.*going now.*",
     ["Alright! Have a great time and see you soon!",
      "Okay! I’ll be here whenever you need more info.",
      "Take care! Reach out anytime for MGEU-related help."]]
]